version: "3.9"
services:
  app:
    container_name: nest_course
    depends_on:
      - postgres
    restart: always
    build: .
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/db
      NODE_ENV: development
      PORT: 3003
    ports:
      - "3003:3003"
    volumes:
      - "./:/usr/src/app"
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "35432:5432"
    volumes:
      - "./data:/data/db"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
